version: "3.3"

services:
    nginx:
        restart: always
        container_name: magento_nginx
        image: nginx:latest
        working_dir: /var/www/
        volumes:
            -   ./src:/var/www
            -   ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            -   "1908:80"
        expose:
            -   "80"
        links:
            -   "app"
    app:
        build:
            context: ./docker/php8.1-fpm
        container_name: app
        working_dir: /var/www/
        volumes:
            -   ./src/:/var/www/
        restart: always
        expose:
            -   "9000"
        depends_on:
            -   mysql
            -   redis
            -   elasticsearch
        links:
            -   "mysql:database"
            -   "elasticsearch:elasticsearch"
    mysql:
        restart: always
        image: mysql:latest
        container_name: magento_mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        working_dir: /var/lib/mysql
        volumes:
            -   ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: magento2
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: mysql_password
            MYSQL_ROOT_PASSWORD: mysql_root_password
        expose:
            -   "3306"
    elasticsearch:
        user: root
        container_name: magento_elasticsearch
        build:
            context: ./docker/elasticsearch
        environment:
            -   node.name=magento_elasticsearch
            -   cluster.name=docker-cluster
            -   bootstrap.memory_lock=true
            -   "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            -   "discovery.type=single-node"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            -   ./data/elasticsearch:/usr/share/elasticsearch/data
        expose:
            -   "9200"
