<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<?php
/**
 * @var \Modules\ExchangeRate\Block\ExchangeRateBlock $block
 */
?>
<?php 
 $er_url = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=68";
 $ch = curl_init();
 curl_setopt($ch, CURLOPT_URL, $er_url);
 curl_setopt($ch, CURLOPT_FAILONERROR, 1);
 curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
 curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
 curl_setopt($ch, CURLOPT_TIMEOUT, 15);
 curl_setopt($ch, CURLOPT_VERBOSE, true);
 curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
 curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
 $res = curl_exec($ch);
 curl_close($ch);
 $xml = simplexml_load_string($res);
 $json = json_encode($xml);
 $data = json_decode($json, TRUE);
?>

<div class = "container">
<h3 class="text-center">Bảng quy đổi tiền tệ Vietcombank <?= $data['DateTime'] ?></h3>
<table class="table">
    <thead>
    <tr>
        <th scope="col"><h5>STT</h5></th>
        <th scope="col"><h5>Mã</h5></th>
        <th scope="col"><h5>Tên</h5></th>
        <th scope="col"><h5>Giá mua</h5></th>
        <th scope="col"><h5>Giá bán</h5></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data['Exrate'] as $k => $currency): ?>
    <tr>
        <td scope="row"><h5><?= $k+1 ?></h5></td>
        <td style="font-size: 1.25rem;">
            <img src="https://wise.com/public-resources/assets/flags/rectangle/<?= substr(strtolower($currency['@attributes']['CurrencyCode']), 0) ?>.png" style="width:38px;height:26px;">
            <?= $currency['@attributes']['CurrencyCode'] ?>
        </td>
        <td><h5><?= $currency['@attributes']['CurrencyName'] ?></h5></td>
        <td><h5><?= $currency['@attributes']['Buy'] ?></h5></td>
        <td><h5><?= $currency['@attributes']['Sell'] ?></h5></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</div>